apiVersion: apps/v1
kind: Deployment
metadata:
  name: managed-velero-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: managed-velero-operator
  template:
    metadata:
      labels:
        name: managed-velero-operator
    spec:
      serviceAccountName: managed-velero-operator
      containers:
        - name: managed-velero-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - managed-velero-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "managed-velero-operator"
